#!/usr/bin/env bash

# ============================================================================
# SYSTEM HARDENING SCRIPT
# ============================================================================
# Description: Initial security setup for brennan.cafe homelab
# Author: Brennan Kenneth Brown
# Usage: sudo ./01-system-hardening.sh
# ============================================================================

set -euo pipefail  # Exit on error, undefined vars, pipe failures

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

print_header() {
    echo -e "\n${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  $1${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
}

print_info() {
    echo -e "${YELLOW}➜${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        print_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# ============================================================================
# PRE-FLIGHT CHECKS
# ============================================================================

print_header "🔒 System Hardening for brennan.cafe"

check_root

print_info "Checking system..."
echo "  Hostname: $(hostname)"
echo "  User: $SUDO_USER"
echo "  OS: $(lsb_release -ds)"
echo ""

read -p "Continue with system hardening? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_error "Aborted by user"
    exit 1
fi

# ============================================================================
# SYSTEM UPDATES
# ============================================================================

print_header "📦 System Updates"

print_info "Updating package lists..."
apt update -qq

print_info "Upgrading installed packages..."
apt upgrade -y

print_info "Installing essential packages..."
apt install -y \
    ufw \
    fail2ban \
    unattended-upgrades \
    apt-listchanges \
    curl \
    wget \
    git \
    htop \
    tree \
    micro \
    net-tools \
    dnsutils \
    lm-sensors \
    build-essential

print_success "System updated and essential packages installed"

# ============================================================================
# SSH CONFIGURATION
# ============================================================================

print_header "🔐 SSH Hardening"

# Backup original sshd_config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

print_info "Configuring SSH daemon..."

# Create secure SSH config
cat > /etc/ssh/sshd_config.d/99-hardening.conf << 'EOF'
# SSH Hardening Configuration for brennan.cafe
# Generated by system-hardening script

# Only allow key-based authentication
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no

# Security settings
PermitRootLogin no
MaxAuthTries 3
MaxSessions 5

# Network settings
Port 22
AddressFamily inet
ListenAddress 0.0.0.0

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Timing
ClientAliveInterval 300
ClientAliveCountMax 2

# Other security
X11Forwarding no
AllowTcpForwarding yes
PermitTunnel no
UsePAM yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

print_info "Adding authorized SSH key..."

# Ensure .ssh directory exists for user
sudo -u $SUDO_USER mkdir -p /home/$SUDO_USER/.ssh
sudo -u $SUDO_USER chmod 700 /home/$SUDO_USER/.ssh

# Add the authorized key
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAYU6lvu3nmR49iW0mK/Lrqs4P02ouw2wZq1Sa5LkU2v brennan@omg.lol" \
    | sudo -u $SUDO_USER tee /home/$SUDO_USER/.ssh/authorized_keys > /dev/null

sudo -u $SUDO_USER chmod 600 /home/$SUDO_USER/.ssh/authorized_keys

print_info "Testing SSH configuration..."
if sshd -t; then
    print_success "SSH configuration valid"
    systemctl restart sshd
    print_success "SSH daemon restarted"
else
    print_error "SSH configuration invalid - reverting changes"
    rm /etc/ssh/sshd_config.d/99-hardening.conf
    exit 1
fi

print_success "SSH hardened successfully"

# ============================================================================
# FIREWALL (UFW)
# ============================================================================

print_header "🛡️  Firewall Setup (UFW)"

print_info "Configuring UFW firewall..."

# Reset UFW to defaults
ufw --force reset

# Default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH (IMPORTANT: Do this before enabling!)
ufw allow 22/tcp comment 'SSH'

# Allow HTTP and HTTPS (for Caddy/web services)
ufw allow 80/tcp comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'

# Enable UFW
print_info "Enabling firewall..."
ufw --force enable

# Show status
ufw status verbose

print_success "Firewall configured and enabled"

# ============================================================================
# FAIL2BAN
# ============================================================================

print_header "🚫 Fail2Ban Setup"

print_info "Configuring Fail2Ban..."

# Create local jail configuration
cat > /etc/fail2ban/jail.local << 'EOF'
# Fail2Ban configuration for brennan.cafe
# Auto-bans IPs after failed login attempts

[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 5
destemail = mail@brennanbrown.ca
sendername = Fail2Ban-brennan.cafe
action = %(action_mw)s

[sshd]
enabled = true
port = 22
logpath = /var/log/auth.log
maxretry = 3
bantime = 24h
EOF

# Start and enable Fail2Ban
systemctl enable fail2ban
systemctl restart fail2ban

print_success "Fail2Ban configured and running"

# ============================================================================
# AUTOMATIC UPDATES
# ============================================================================

print_header "🔄 Automatic Security Updates"

print_info "Configuring unattended upgrades..."

# Configure automatic security updates
cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
// Automatic security updates for brennan.cafe

Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

Unattended-Upgrade::AutoFixInterruptedDpkg "true";
Unattended-Upgrade::MinimalSteps "true";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";
EOF

# Enable automatic updates
cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOF

print_success "Automatic security updates enabled"

# ============================================================================
# SYSTEM HARDENING
# ============================================================================

print_header "🔧 Additional Hardening"

print_info "Setting file permissions..."

# Secure important files
chmod 644 /etc/passwd
chmod 640 /etc/shadow
chmod 644 /etc/group
chmod 640 /etc/gshadow

print_info "Disabling unnecessary services..."

# Disable Bluetooth (not needed on a server)
systemctl disable bluetooth.service 2>/dev/null || true

print_info "Configuring kernel parameters..."

# Sysctl hardening
cat > /etc/sysctl.d/99-brennan-cafe-hardening.conf << 'EOF'
# Network security hardening for brennan.cafe

# IP Forwarding (disabled unless needed for Docker)
net.ipv4.ip_forward = 0

# SYN cookies protection
net.ipv4.tcp_syncookies = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0

# Ignore source routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# Log martian packets
net.ipv4.conf.all.log_martians = 1

# Protect against tcp time-wait assassination
net.ipv4.tcp_rfc1337 = 1
EOF

sysctl -p /etc/sysctl.d/99-brennan-cafe-hardening.conf

print_success "Additional hardening applied"

# ============================================================================
# SUMMARY
# ============================================================================

print_header "✨ System Hardening Complete"

echo "The following security measures have been applied:"
echo ""
echo "  ✓ System updated to latest packages"
echo "  ✓ SSH hardened (key-only authentication)"
echo "  ✓ Firewall enabled (UFW)"
echo "  ✓ Fail2Ban configured"
echo "  ✓ Automatic security updates enabled"
echo "  ✓ Additional kernel hardening applied"
echo ""
echo "Next steps:"
echo "  1. Test SSH access from another machine"
echo "  2. Run: ./02-install-docker.sh"
echo "  3. Keep this system updated regularly"
echo ""
print_info "IMPORTANT: Test SSH access before closing this session!"
echo ""

# Show security status
print_header "🔍 Security Status"
echo "SSH Status:"
systemctl status sshd --no-pager | head -n 3
echo ""
echo "Firewall Status:"
ufw status | head -n 10
echo ""
echo "Fail2Ban Status:"
systemctl status fail2ban --no-pager | head -n 3
echo ""

print_success "System is now hardened and ready for brennan.cafe services 🌻"